label jasmineliga:
    play sound "sound/Toquedocel.wav"
    pause 2
    "Hum?"
    show phone at right with zoomin:
        zoom 0.7
    play sound "sound/Toquedocel.wav"
    pause 1
    Dory "Alô?"
    Jasmine "Oiii Doryyy!"
    Dory "Oi amiga!"
    Jasmine "Ainnn que lindaa!"
    Jasmine "Ela se lembrou de mim!"
    Dory "Err, um pouco sim..."
    Jasmine "Tô tão feliz!"
    Jasmine "Liguei pra te avisar que já estou quase chegando."
    Jasmine "Esse hospital é muito longe."
    Dory "Pois é, eu estou percebendo."
    Dory "Longe e quase abandonado."
    Dory "Que bom que foi a doutora Karen quem me atendeu."
    Dory "Ela parece ser a mais sensata aqui."
    Jasmine "Se cuida amiga."
    Dory "Pode deixar."
    menu:
        "A propósito, você quer ficar com o Yuri?":
            Jasmine "O QUÊÊÊÊÊ???"
            Jasmine "De onde você tirou essa ideia?"
            Dory "Ele mesmo me contou..."
            Jasmine "O que aquele babaca idiota insinuou?"
            Dory "Disse que por eu não ter ido na festa dele, quem quis ficar com ele foi você!"
            Jasmine "Espera..."
            Jasmine "VOCÊ TAVA PEGANDO ESSE CANALHA NOJENTO?"
            Dory "Espero que não."
            Dory "Não me lembro."
            Jasmine "Ah é, esqueci."
            Dory "O Jonas não merece isso."
            Jasmine "Realmente."
            Jasmine "Entre os dois eu prefiro o magrelo."
            Dory "O que tem com vocês dois dizendo que ele é magrelo?"
            Dory "Pelo que eu me {color=#f99}lembro{/color}, ele até que é bonito..."
            Dory "ESPERA, AMIGA, EU ME LEMBREI DELE!"
            Jasmine "VERDADE AMIGA!"
            Jasmine "Mas 'bonito'? Só você mesma Dory..."
            Jasmine "Enfim, to quase chegando, meu pai está me levando."
            Dory "Achei que você estava dirigindo esse tempo todo."
            Jasmine "Não sou irresponsável igual certas pessoas..."
            Dory "Isso foi uma indireta?"
            Jasmine "Hahaha."
            Jasmine "Beijo amiga."
            Dory "Tchau..."
            play sound "sound/Phoneend.wav"
            hide phone
            pause 1
        "Não dizer nada":
            Dory ". . ."
            Jasmine "Beijo amiga."
            Dory "Tchau..."
            Jasmine "Você ficou estranha de repente..."
            Jasmine "Aconteceu alguma coisa?"
            Dory "Nada não."
            Jasmine "Eu te conheço fofa, está querendo dizer algo e está com medo da minha reação."
            Jasmine "Somos amigas, pode falar..."
            Dory "Promete não ficar braba comigo?"
            Jasmine "Você está me assustando."
            Jasmine "Mas sim prometo, agora diga."
            Dory "Você quer ficar com o Yuri?"
            Jasmine "O QUÊÊÊÊÊ???"
            Jasmine "De onde você tirou essa ideia?"
            Dory "Ele mesmo me contou..."
            Jasmine "O que aquele babaca idiota insinuou?"
            Dory "Disse que por eu não ter ido na festa dele, quem quis ficar com ele foi você!"
            Jasmine "Espera..."
            Jasmine "VOCÊ TAVA PEGANDO ESSE CANALHA NOJENTO?"
            Dory "Espero que não."
            Dory "Não me lembro."
            Jasmine "Ah é, esqueci."
            Dory "O Jonas não merece isso."
            Jasmine "Realmente."
            Jasmine "Entre os dois eu prefiro o magrelo."
            Dory "O que tem com vocês dois dizendo que ele é magrelo?"
            Dory "Pelo que eu me {color=#f99}lembro{/color}, ele até que é bonito..."
            Dory "ESPERA, AMIGA, EU ME LEMBREI DELE!"
            Jasmine "VERDADE AMIGA!"
            Jasmine "Mas 'bonito'? Só você mesma Dory..."
            Jasmine "Enfim, to quase chegando, meu pai está me levando."
            Dory "Achei que você estava dirigindo esse tempo todo."
            Jasmine "Não sou irresponsável igual certas pessoas..."
            Dory "Isso foi uma indireta?"
            Jasmine "Hahaha."
            Jasmine "Agora eu preciso desligar."
            Dory "Beijos."
            Jasmine "Tchau tchau!"
            play sound "sound/Phoneend.wav"
            hide phone
            pause 1

"Ai como eu estou feliz por estar começando a me lembrar das coisas!"
"O Jonas deve significar muito para mim..."
"Afinal eu me lembrei primeiro da aparência dele do que a da minha própria mãe!"
pause 1
"Hum?"
jump resultadoexame
